---

- name: Add proxy to /etc/environment
  become: true
  blockinfile:
    path: /etc/environment
    block: |
      http_proxy="http://wwwproxy.unimelb.edu.au:8000"
      https_proxy="http://wwwproxy.unimelb.edu.au:8000"
      ftp_proxy="http://wwwproxy.unimelb.edu.au:8000"
      no_proxy=localhost,127.0.0.1,127.0.1.1,ubuntu,ccc_3.novalocal,ccc_3


- name: apt-get update
  become: true
  apt:
    force_apt_get: yes
    update_cache: yes


- name: install the packages using apt modules
  become: true
  apt:
    state: latest
    update_cache: yes
    name: ['python3-pip', 'git', 'vim', 'couchdb']


- name: mkdir the mount point
  become: true
  file:
    path: /data
    state: directory
    owner: ubuntu
    group: ubuntu
    mode: 0755


- name: mkdir the /data/workspace
  become: true
  file:
    path: "{{ item }}"
    state: directory
    owner: ubuntu
    group: ubuntu
    mode: 0777
  with_items:
    - /data/workspace

- name: checkout from github
  become: true
  command: git clone https://github.com/Neetordy/Cluster_and_Cloud_Computing.git
  args:
    chdir: /data/workspace
    creates: /data/workspace/Cluster_and_Cloud_Computing

- name: install environemnt
  become: true
  command: pip3 install {{ item }}
  with_items:
    - tweepy
    - urllib3
    - couchdb


- name: run harvest script
  become: true
  command: python3 /data/workspace/Cluster_and_Cloud_Computing/Harvest/tweets.py &
