---

- name: Add proxy to /etc/environment
  become: true
  blockinfile:
    path: /etc/environment
    block: |
      http_proxy="http://wwwproxy.unimelb.edu.au:8000"
      https_proxy="http://wwwproxy.unimelb.edu.au:8000"
      ftp_proxy="http://wwwproxy.unimelb.edu.au:8000"
      no_proxy=localhost,127.0.0.1,127.0.1.1,ubuntu,ccc_2.novalocal,ccc_2


- name: apt-get update
  become: true
  apt:
    force_apt_get: yes
    update_cache: yes


- name: install the packages using apt modules
  become: true
  apt:
    state: latest
    update_cache: yes
    name: ['python3-pip', 'git', 'vim', 'couchdb']


- name: mkdir the mount point
  become: true
  file:
    path: /data
    state: directory
    owner: ubuntu
    group: ubuntu
    mode: 0755


- name: mkdir the /data/workspace
  become: true
  file:
    path: "{{ item }}"
    state: directory
    owner: ubuntu
    group: ubuntu
    mode: 0777
  with_items:
    - /data/workspace


- name: checkout from github
  become: true
  command: git clone https://github.com/Neetordy/Cluster_and_Cloud_Computing.git
  args:
    chdir: /data/workspace
    creates: /data/workspace/Cluster_and_Cloud_Computing

- name: install environemnt
  become: true
  command: pip3 install {{ item }}
  with_items:
    - tweepy
    - urllib3
    - couchdb

 - name: config couchDB
   become: true
   shell: |
     cd /opt/couchdb/etc
     sed -i "s/;admin = mysecretpassword/admin = nmsl" local.ini
     sed -i 's/127.0.0.1/0.0.0.0/g' default.ini
     cd /opt/couchdb/releases/2.3.1;rm -rf sys.config
     sed -i "s/-name couchdb@127.0.0.1/-name couchdb@$(ip route get 8.8.8.8 | awk '{print $NF; exit}')/g" /opt/couchdb/etc/vm.args


- name: create cluster
  become: true
  commamd:  curl -X PUT "http://admin:nmsl@172.26.38.7:5986/_nodes/couchdb@172.26.37.253" -d {}

- name: run CouchDC
  become: true
  shell: service couchdb start