---
- name: Create Volume(s)
  os_volume:
    display_name: '{{ item.vol_name }}'
    size: '{{ item.vol_size }}'
    availability_zone: '{{ availability_zone }}'
    wait: yes
    timeout: 600
    state: present
  loop: '{{ volumes }}'
  register: os_vol

- name: Create a list of volume Ids
  set_fact:
    os_vol_ids: '{{ os_vol_ids|default([]) + [ item.id ] }}'
  loop: '{{ os_vol.results }}'

- debug:
    msg: "Volume {{ os_vol_ids }} has been created."

- name: Create an instance
  os_server:
    name: '{{ instance_name }}'
    image: '{{ instance_image }}'
    key_name: '{{ instance_key_name }}'
    flavor: '{{ instance_flavor }}'
    availability_zone: '{{ availability_zone }}'
    security_groups: '{{ security_groups }}'
    volumes: '{{ os_vol_ids }}'
    auto_floating_ip: yes
    wait: yes
    timeout: 600
    state: present
  register: os_instance

- debug:
    msg: "Instance {{ instance_name}} has been created. IP address is {{ os_instance.openstack.public_v4 }}"
  when: os_instance.openstack is defined


- name: add IP to hosts file
  lineinfile:
    dest: ./hosts
    line: '{{ os_instance.openstack.public_v4 }}'



#  http_proxy="http://wwwproxy.unimelb.edu.au:8000"
#  https_proxy="http://wwwproxy.unimelb.edu.au:8000"
#  ftp_proxy="http://wwwproxy.unimelb.edu.au:8000"
#  no_pro{{ os_instance.openstack.public_v4 }}xy=localhost,127.0.0.1,127.0.1.1,ubuntu,ccc_2.novalocal,ccc_2